/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PaperclipPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/api.ts
var import_obsidian = require("obsidian");
var PaperclipApi = class {
  constructor(baseUrl, apiKey) {
    this.baseUrl = baseUrl;
    this.apiKey = apiKey;
  }
  updateConfig(baseUrl, apiKey) {
    this.baseUrl = baseUrl.replace(/\/+$/, "");
    this.apiKey = apiKey;
  }
  async request(method, path, body) {
    var _a, _b;
    const url = `${this.baseUrl}${path}`;
    const headers = {
      "Content-Type": "application/json"
    };
    if (this.apiKey) {
      headers["Authorization"] = `Bearer ${this.apiKey}`;
    }
    const params = {
      url,
      method,
      headers,
      throw: false
    };
    if (body) {
      const clean = {};
      for (const [k, v] of Object.entries(body)) {
        if (v !== void 0) clean[k] = v;
      }
      params.body = JSON.stringify(clean);
    }
    const resp = await (0, import_obsidian.requestUrl)(params);
    if (resp.status >= 400) {
      const msg = ((_a = resp.json) == null ? void 0 : _a.error) || ((_b = resp.json) == null ? void 0 : _b.message) || `HTTP ${resp.status}`;
      throw new Error(msg);
    }
    return resp.json;
  }
  // Companies
  async listCompanies() {
    return this.request("GET", "/api/companies");
  }
  // Issues
  async listIssues(companyId, filters) {
    const params = new URLSearchParams();
    if (filters == null ? void 0 : filters.status) params.set("status", filters.status);
    if (filters == null ? void 0 : filters.assigneeAgentId)
      params.set("assigneeAgentId", filters.assigneeAgentId);
    if (filters == null ? void 0 : filters.projectId) params.set("projectId", filters.projectId);
    if (filters == null ? void 0 : filters.q) params.set("q", filters.q);
    const qs = params.toString();
    const path = `/api/companies/${companyId}/issues${qs ? `?${qs}` : ""}`;
    return this.request("GET", path);
  }
  async getIssue(issueId) {
    return this.request("GET", `/api/issues/${issueId}`);
  }
  async createIssue(companyId, data) {
    return this.request(
      "POST",
      `/api/companies/${companyId}/issues`,
      data
    );
  }
  async updateIssue(issueId, patch) {
    return this.request(
      "PATCH",
      `/api/issues/${issueId}`,
      patch
    );
  }
  // Comments
  async listComments(issueId) {
    return this.request(
      "GET",
      `/api/issues/${issueId}/comments`
    );
  }
  async addComment(issueId, body) {
    return this.request(
      "POST",
      `/api/issues/${issueId}/comments`,
      { body }
    );
  }
  // Agents
  async listAgents(companyId) {
    return this.request(
      "GET",
      `/api/companies/${companyId}/agents`
    );
  }
  // Projects
  async listProjects(companyId) {
    return this.request(
      "GET",
      `/api/companies/${companyId}/projects`
    );
  }
  async createProject(companyId, name) {
    return this.request(
      "POST",
      `/api/companies/${companyId}/projects`,
      { name, status: "planned" }
    );
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  apiBaseUrl: "http://localhost:3100",
  apiKey: "",
  defaultCompanyId: "",
  refreshIntervalSec: 60,
  openaiApiKey: ""
};
var PaperclipSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("API base URL").setDesc("Paperclip server URL (e.g. http://localhost:3100)").addText(
      (text) => text.setPlaceholder("http://localhost:3100").setValue(this.plugin.settings.apiBaseUrl).onChange(async (value) => {
        this.plugin.settings.apiBaseUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("API key").setDesc(
      "Optional bearer token for authenticated/private mode instances"
    ).addText(
      (text) => text.setPlaceholder("Leave empty for local_trusted mode").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Default company ID").setDesc(
      "Company to select on open (leave empty to show selector)"
    ).addText(
      (text) => text.setPlaceholder("UUID").setValue(this.plugin.settings.defaultCompanyId).onChange(async (value) => {
        this.plugin.settings.defaultCompanyId = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("OpenAI API key").setDesc(
      "For AI-powered issue creation from selected text"
    ).addText(
      (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
        this.plugin.settings.openaiApiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Refresh interval").setDesc("Auto-refresh issue list (seconds, 0 to disable)").addText(
      (text) => text.setPlaceholder("60").setValue(
        String(this.plugin.settings.refreshIntervalSec)
      ).onChange(async (value) => {
        const n = parseInt(value, 10);
        if (!isNaN(n) && n >= 0) {
          this.plugin.settings.refreshIntervalSec = n;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/views/PaperclipView.ts
var import_obsidian7 = require("obsidian");

// src/views/CommentModal.ts
var import_obsidian3 = require("obsidian");
var CommentModal = class extends import_obsidian3.Modal {
  constructor(app, issue, agents, onSubmit) {
    super(app);
    this.body = "";
    this.selectedAgentId = "";
    this.issue = issue;
    this.agents = agents;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    var _a, _b;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", {
      text: `Comment on ${this.issue.identifier}`
    });
    if (this.agents.length > 0) {
      const currentName = this.issue.assigneeAgentId ? (_b = (_a = this.agents.find((a) => a.id === this.issue.assigneeAgentId)) == null ? void 0 : _a.name) != null ? _b : "Unknown" : "Unassigned";
      new import_obsidian3.Setting(contentEl).setName("Assign to agent").setDesc(`Currently: ${currentName}`).addDropdown((dd) => {
        dd.addOption("", "\u2014 No change \u2014");
        for (const a of this.agents) {
          dd.addOption(a.id, `${a.name} (${a.role})`);
        }
        dd.setValue(this.selectedAgentId);
        dd.onChange((v) => {
          this.selectedAgentId = v;
        });
      });
    }
    if (this.agents.length > 0) {
      const hint = contentEl.createDiv({ cls: "paperclip-mention-hint" });
      hint.createSpan({ text: "Mention agents: " });
      for (const a of this.agents) {
        const chip = hint.createEl("button", {
          text: `@${a.name}`,
          cls: "paperclip-mention-chip"
        });
        chip.addEventListener("click", () => {
          this.body += ` @${a.name} `;
          textarea.setValue(this.body);
        });
      }
    }
    let textarea;
    new import_obsidian3.Setting(contentEl).setName("Comment body").setDesc("Markdown supported. Use @AgentName to mention.").addTextArea((ta) => {
      textarea = ta;
      ta.setPlaceholder("Write your comment\u2026").setValue(this.body).onChange((v) => {
        this.body = v;
      });
      ta.inputEl.rows = 8;
      ta.inputEl.addClass("paperclip-comment-textarea");
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Post comment").setCta().onClick(() => {
        if (!this.body.trim()) return;
        btn.setDisabled(true);
        btn.setButtonText("Posting\u2026");
        void this.onSubmit({
          body: this.body,
          assignAgentId: this.selectedAgentId || void 0
        }).then(() => {
          this.close();
        });
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/views/AssignModal.ts
var import_obsidian4 = require("obsidian");
var ASSIGN_TO_ME = "__me__";
var AssignModal = class extends import_obsidian4.SuggestModal {
  constructor(app, agents, onChoose) {
    super(app);
    this.agents = agents;
    this.onChoose = onChoose;
    this.setPlaceholder("Select agent to assign\u2026");
  }
  getSuggestions(query) {
    const q = query.toLowerCase();
    const options = [
      { agent: null, display: "\u{1F464} Assign to me", special: ASSIGN_TO_ME },
      { agent: null, display: "Unassign" },
      ...this.agents.map((a) => ({
        agent: a,
        display: `${a.name} \u2014 ${a.role}${a.title ? ` (${a.title})` : ""} [${a.status}]`
      }))
    ];
    if (!q) return options;
    return options.filter((o) => o.display.toLowerCase().includes(q));
  }
  renderSuggestion(item, el) {
    el.createDiv({ text: item.display });
  }
  onChooseSuggestion(item) {
    void this.onChoose(item.agent, item.special);
  }
};

// src/views/CreateIssueModal.ts
var import_obsidian5 = require("obsidian");
var ASSIGN_ME_ID = "__me__";
var CreateIssueModal = class extends import_obsidian5.Modal {
  constructor(app, agents, projects, activeFilePath, defaultProjectId, onSubmit, prefill) {
    var _a, _b, _c, _d;
    super(app);
    this.issueTitle = "";
    this.description = "";
    this.priority = "medium";
    this.selectedAgentId = "";
    this.selectedProjectId = "";
    this.includeFilePath = false;
    this.agents = agents;
    this.projects = projects;
    this.activeFilePath = activeFilePath;
    this.selectedProjectId = (_a = prefill == null ? void 0 : prefill.projectId) != null ? _a : defaultProjectId;
    this.onSubmit = onSubmit;
    if (prefill) {
      this.issueTitle = (_b = prefill.title) != null ? _b : "";
      this.description = (_c = prefill.description) != null ? _c : "";
      this.priority = (_d = prefill.priority) != null ? _d : "medium";
      if (prefill.assigneeAgentId) this.selectedAgentId = prefill.assigneeAgentId;
    }
    if (!this.selectedAgentId) {
      const ceo = agents.find((a) => a.role === "ceo");
      if (ceo) this.selectedAgentId = ceo.id;
    }
  }
  onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("paperclip-create-modal");
    contentEl.createEl("h3", { text: "Create issue" });
    new import_obsidian5.Setting(contentEl).setName("Title").addText(
      (text) => text.setPlaceholder("Issue title").setValue(this.issueTitle).onChange((v) => {
        this.issueTitle = v;
      })
    );
    new import_obsidian5.Setting(contentEl).setName("Description").addTextArea((ta) => {
      ta.setPlaceholder("Describe the issue\u2026").setValue(this.description).onChange((v) => {
        this.description = v;
      });
      ta.inputEl.rows = 6;
      ta.inputEl.addClass("paperclip-comment-textarea");
    });
    if (this.projects.length > 0) {
      new import_obsidian5.Setting(contentEl).setName("Project").addDropdown((dd) => {
        dd.addOption("", "\u2014 No project \u2014");
        for (const p of this.projects.filter((p2) => !p2.archivedAt)) {
          dd.addOption(p.id, p.name);
        }
        dd.setValue(this.selectedProjectId);
        dd.onChange((v) => {
          this.selectedProjectId = v;
        });
      });
    }
    new import_obsidian5.Setting(contentEl).setName("Assign to").addDropdown((dd) => {
      dd.addOption(ASSIGN_ME_ID, "\u{1F464} Assign to me");
      dd.addOption("", "\u2014 Unassigned \u2014");
      for (const a of this.agents) {
        dd.addOption(a.id, `${a.name} (${a.role})`);
      }
      dd.setValue(this.selectedAgentId);
      dd.onChange((v) => {
        this.selectedAgentId = v;
      });
    });
    new import_obsidian5.Setting(contentEl).setName("Include current file as context").setDesc((_a = this.activeFilePath) != null ? _a : "No file open").addToggle((toggle) => {
      toggle.setValue(this.includeFilePath);
      if (!this.activeFilePath) {
        toggle.setDisabled(true);
      } else {
        toggle.onChange((v) => {
          this.includeFilePath = v;
        });
      }
    });
    new import_obsidian5.Setting(contentEl).setName("Priority").addDropdown((dd) => {
      dd.addOption("critical", "Critical");
      dd.addOption("high", "High");
      dd.addOption("medium", "Medium");
      dd.addOption("low", "Low");
      dd.setValue(this.priority);
      dd.onChange((v) => {
        this.priority = v;
      });
    });
    let submitting = false;
    const doSubmit = async () => {
      if (submitting || !this.issueTitle.trim()) return;
      submitting = true;
      let desc = this.description;
      if (this.includeFilePath && this.activeFilePath) {
        const ctx = `

---
**Context:** \`${this.activeFilePath}\``;
        desc = desc ? desc + ctx : ctx.trim();
      }
      const isMe = this.selectedAgentId === ASSIGN_ME_ID;
      await this.onSubmit({
        title: this.issueTitle,
        description: desc,
        priority: this.priority,
        assigneeAgentId: isMe ? void 0 : this.selectedAgentId || void 0,
        assignToMe: isMe,
        projectId: this.selectedProjectId || void 0
      });
      this.close();
    };
    new import_obsidian5.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create issue").setCta().onClick(() => {
        void doSubmit();
      })
    );
    contentEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        void doSubmit();
      }
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/views/ProjectModal.ts
var import_obsidian6 = require("obsidian");
var ProjectModal = class extends import_obsidian6.SuggestModal {
  constructor(app, projects, onChoose, onCreate) {
    super(app);
    this.projects = projects;
    this.onChoose = onChoose;
    this.onCreate = onCreate != null ? onCreate : null;
    this.setPlaceholder("Select or type to create project\u2026");
  }
  getSuggestions(query) {
    const q = query.toLowerCase().trim();
    const existing = this.projects.filter((p) => !p.archivedAt).map((p) => ({ project: p, display: p.name }));
    const filtered = q ? existing.filter((o) => o.display.toLowerCase().includes(q)) : existing;
    const options = [
      { project: null, display: "\u2014 No project \u2014" },
      ...filtered
    ];
    if (q && this.onCreate && !existing.some((o) => o.display.toLowerCase() === q)) {
      options.push({
        project: null,
        display: `+ Create "${query.trim()}"`,
        isCreate: true,
        createName: query.trim()
      });
    }
    return options;
  }
  renderSuggestion(item, el) {
    if (item.isCreate) {
      el.createDiv({ text: item.display, cls: "paperclip-create-option" });
    } else {
      el.createDiv({ text: item.display });
    }
  }
  onChooseSuggestion(item) {
    if (item.isCreate && item.createName && this.onCreate) {
      void this.onCreate(item.createName).then((newProject) => {
        void this.onChoose(newProject);
      });
    } else {
      void this.onChoose(item.project);
    }
  }
};

// src/views/PaperclipView.ts
var VIEW_TYPE = "paperclip-view";
var KANBAN_STATUSES = [
  "backlog",
  "todo",
  "in_progress",
  "in_review",
  "blocked",
  "done",
  "cancelled"
];
var PaperclipView = class extends import_obsidian7.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.companies = [];
    this.agents = [];
    this.projects = [];
    this.issues = [];
    this.selectedCompanyId = "";
    this.selectedProjectId = "";
    this.statusFilter = "all";
    this.viewMode = "list";
    this.groupBy = "status";
    this.selectedIssue = null;
    this.comments = [];
    this.refreshTimer = null;
    /** Track which issues had activeRun on last poll, keyed by issue id */
    this.previouslyRunning = /* @__PURE__ */ new Map();
    /** Cache of contributing agent IDs per issue */
    this.contributors = /* @__PURE__ */ new Map();
    /** Track collapsed section groups in list view */
    this.collapsedGroups = /* @__PURE__ */ new Set();
    /** Issues related to the currently active file */
    this.relatedIssues = [];
    /** Path of the file whose related issues are currently loaded */
    this.relatedFilePath = null;
    this.plugin = plugin;
  }
  // Public accessors for main.ts AI features
  getAgents() {
    return this.agents;
  }
  getProjects() {
    return this.projects;
  }
  getSelectedCompanyId() {
    return this.selectedCompanyId;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Paperclip";
  }
  getIcon() {
    return "paperclip";
  }
  async onOpen() {
    await this.loadCompanies();
    this.render();
    this.startAutoRefresh();
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        void this.onActiveFileChange();
      })
    );
    void this.onActiveFileChange();
  }
  onClose() {
    this.stopAutoRefresh();
  }
  // ── Data loading ───────────────────────────────────────────────
  async loadCompanies() {
    try {
      this.companies = await this.plugin.api.listCompanies();
      if (this.plugin.settings.defaultCompanyId && !this.selectedCompanyId) {
        this.selectedCompanyId = this.plugin.settings.defaultCompanyId;
      }
      if (!this.selectedCompanyId && this.companies.length > 0) {
        this.selectedCompanyId = this.companies[0].id;
      }
      if (this.selectedCompanyId) {
        await this.loadAgents();
        await this.loadProjects();
        await this.loadIssues();
      }
    } catch (e) {
      new import_obsidian7.Notice(`Paperclip: failed to load companies \u2014 ${e}`);
    }
  }
  async loadAgents() {
    if (!this.selectedCompanyId) return;
    try {
      this.agents = await this.plugin.api.listAgents(
        this.selectedCompanyId
      );
    } catch (e) {
      this.agents = [];
    }
  }
  async loadProjects() {
    if (!this.selectedCompanyId) return;
    try {
      this.projects = await this.plugin.api.listProjects(
        this.selectedCompanyId
      );
    } catch (e) {
      this.projects = [];
    }
  }
  async loadIssues() {
    if (!this.selectedCompanyId) return;
    try {
      const statusMap = {
        active: "backlog,todo,in_progress,blocked,in_review",
        done: "done,cancelled",
        all: void 0
      };
      this.issues = await this.plugin.api.listIssues(
        this.selectedCompanyId,
        {
          status: statusMap[this.statusFilter],
          projectId: this.selectedProjectId || void 0
        }
      );
    } catch (e) {
      new import_obsidian7.Notice(`Paperclip: failed to load issues \u2014 ${e}`);
      this.issues = [];
    }
  }
  async onActiveFileChange() {
    var _a;
    const file = this.app.workspace.getActiveFile();
    const path = (_a = file == null ? void 0 : file.path) != null ? _a : null;
    if (path === this.relatedFilePath) return;
    this.relatedFilePath = path;
    if (!path || !this.selectedCompanyId) {
      this.relatedIssues = [];
      this.render();
      return;
    }
    await this.loadRelatedIssues(path);
    this.render();
  }
  async loadRelatedIssues(filePath) {
    var _a;
    const basename = (_a = filePath.split("/").pop()) != null ? _a : filePath;
    const name = basename.replace(/\.[^.]+$/, "");
    if (!name || name.length < 3) {
      this.relatedIssues = [];
      return;
    }
    try {
      const results = await this.plugin.api.listIssues(
        this.selectedCompanyId,
        { q: name }
      );
      this.relatedIssues = results;
    } catch (e) {
      this.relatedIssues = [];
    }
  }
  async loadComments(issueId) {
    try {
      this.comments = await this.plugin.api.listComments(issueId);
    } catch (e) {
      this.comments = [];
    }
  }
  agentName(agentId) {
    if (!agentId) return "Unassigned";
    const agent = this.agents.find((a) => a.id === agentId);
    return agent ? agent.name : agentId.slice(0, 8);
  }
  agentInitials(agentId) {
    const name = this.agentName(agentId);
    return name.split(/\s+/).map((w) => w[0]).join("").toUpperCase().slice(0, 2);
  }
  /** Load comment authors for all current issues (fire-and-forget, re-renders when done) */
  loadContributors() {
    const ids = this.issues.map((i) => i.id);
    void Promise.all(
      ids.map(async (id) => {
        var _a;
        try {
          const comments = await this.plugin.api.listComments(id);
          const agentIds = /* @__PURE__ */ new Set();
          const issue = this.issues.find((i) => i.id === id);
          if (issue == null ? void 0 : issue.assigneeAgentId) agentIds.add(issue.assigneeAgentId);
          if ((_a = issue == null ? void 0 : issue.activeRun) == null ? void 0 : _a.agentId) agentIds.add(issue.activeRun.agentId);
          for (const c of comments) {
            if (c.authorAgentId) agentIds.add(c.authorAgentId);
          }
          this.contributors.set(id, [...agentIds]);
        } catch (e) {
        }
      })
    ).then(() => this.render());
  }
  projectName(projectId) {
    if (!projectId) return null;
    const proj = this.projects.find((p) => p.id === projectId);
    return proj ? proj.name : null;
  }
  relativeTime(iso) {
    const diff = Date.now() - new Date(iso).getTime();
    const sec = Math.floor(diff / 1e3);
    if (sec < 60) return "just now";
    const min = Math.floor(sec / 60);
    if (min < 60) return `${min}m ago`;
    const hr = Math.floor(min / 60);
    if (hr < 24) return `${hr}h ago`;
    const days = Math.floor(hr / 24);
    if (days < 30) return `${days}d ago`;
    return new Date(iso).toLocaleDateString();
  }
  // ── Auto-refresh ───────────────────────────────────────────────
  snapshotRunning() {
    this.previouslyRunning.clear();
    for (const issue of this.issues) {
      if (issue.activeRun && issue.activeRun.status === "running") {
        this.previouslyRunning.set(issue.id, {
          identifier: issue.identifier,
          agentId: issue.activeRun.agentId
        });
      }
    }
  }
  detectFinishedRuns() {
    for (const [id, prev] of this.previouslyRunning) {
      const current = this.issues.find((i) => i.id === id);
      const stillRunning = (current == null ? void 0 : current.activeRun) && current.activeRun.status === "running";
      if (!stillRunning) {
        const agentLabel = this.agentName(prev.agentId);
        const status = current ? current.status : "unknown";
        new import_obsidian7.Notice(
          `\u{1F4CE} ${prev.identifier} finished \u2014 ${agentLabel} \u2192 ${status.replace("_", " ")}`,
          8e3
        );
      }
    }
  }
  startAutoRefresh() {
    this.stopAutoRefresh();
    const sec = this.plugin.settings.refreshIntervalSec;
    if (sec > 0) {
      this.refreshTimer = window.setInterval(async () => {
        this.snapshotRunning();
        await this.loadIssues();
        this.detectFinishedRuns();
        if (this.selectedIssue) {
          const updated = this.issues.find(
            (i) => i.id === this.selectedIssue.id
          );
          if (updated) this.selectedIssue = updated;
          await this.loadComments(this.selectedIssue.id);
        }
        this.render();
      }, sec * 1e3);
      this.registerInterval(this.refreshTimer);
    }
  }
  stopAutoRefresh() {
    if (this.refreshTimer !== null) {
      window.clearInterval(this.refreshTimer);
      this.refreshTimer = null;
    }
  }
  // ── Rendering ──────────────────────────────────────────────────
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("paperclip-container");
    if (this.selectedIssue) {
      this.renderDetail(container);
    } else if (this.viewMode === "kanban") {
      this.renderHeader(container);
      this.renderKanban(container);
    } else {
      this.renderHeader(container);
      this.renderRelatedIssues(container);
      this.renderListBody(container);
    }
  }
  renderHeader(container) {
    const header = container.createDiv({ cls: "paperclip-header" });
    const select = header.createEl("select", {
      cls: "paperclip-company-select dropdown"
    });
    for (const c of this.companies) {
      const opt = select.createEl("option", { text: c.name });
      opt.value = c.id;
      if (c.id === this.selectedCompanyId) opt.selected = true;
    }
    select.addEventListener("change", () => {
      this.selectedCompanyId = select.value;
      this.selectedProjectId = "";
      this.selectedIssue = null;
      void this.loadAgents().then(() => this.loadProjects()).then(() => this.loadIssues()).then(() => this.render());
    });
    if (this.projects.length > 0) {
      const projSelect = header.createEl("select", {
        cls: "paperclip-project-select dropdown"
      });
      const allOpt = projSelect.createEl("option", { text: "All projects" });
      allOpt.value = "";
      if (!this.selectedProjectId) allOpt.selected = true;
      for (const p of this.projects.filter((p2) => !p2.archivedAt)) {
        const opt = projSelect.createEl("option", { text: p.name });
        opt.value = p.id;
        if (p.id === this.selectedProjectId) opt.selected = true;
      }
      projSelect.addEventListener("change", () => {
        this.selectedProjectId = projSelect.value;
        void this.loadIssues().then(() => this.render());
      });
    }
    if (this.viewMode === "list") {
      const tabs = header.createDiv({ cls: "paperclip-tabs" });
      const filters = [
        { label: "Active", value: "active" },
        { label: "Done", value: "done" },
        { label: "All", value: "all" }
      ];
      for (const f of filters) {
        const tab = tabs.createEl("button", {
          text: f.label,
          cls: `paperclip-tab${this.statusFilter === f.value ? " is-active" : ""}`
        });
        tab.addEventListener("click", () => {
          this.statusFilter = f.value;
          void this.loadIssues().then(() => this.render());
        });
      }
      const groupTabs = header.createDiv({ cls: "paperclip-tabs" });
      const groupOptions = [
        { label: "By status", value: "status" },
        { label: "By project", value: "project" },
        { label: "By assignee", value: "assignee" }
      ];
      for (const g of groupOptions) {
        const tab = groupTabs.createEl("button", {
          text: g.label,
          cls: `paperclip-tab${this.groupBy === g.value ? " is-active" : ""}`
        });
        tab.addEventListener("click", () => {
          this.groupBy = g.value;
          this.render();
        });
      }
    }
    const headerActions = header.createDiv({ cls: "paperclip-header-actions" });
    const toggleBtn = headerActions.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": this.viewMode === "list" ? "Kanban view" : "List view" }
    });
    (0, import_obsidian7.setIcon)(toggleBtn, this.viewMode === "list" ? "kanban" : "list");
    toggleBtn.addEventListener("click", () => {
      this.viewMode = this.viewMode === "list" ? "kanban" : "list";
      if (this.viewMode === "kanban") {
        this.statusFilter = "all";
        void this.loadIssues().then(() => {
          this.loadContributors();
          this.render();
        });
      } else {
        this.render();
      }
    });
    const newBtn = headerActions.createEl("button", {
      cls: "paperclip-new-issue clickable-icon",
      attr: { "aria-label": "New issue" }
    });
    (0, import_obsidian7.setIcon)(newBtn, "plus");
    newBtn.addEventListener("click", () => {
      this.openCreateIssueModal();
    });
    const refreshBtn = headerActions.createEl("button", {
      cls: "paperclip-refresh clickable-icon",
      attr: { "aria-label": "Refresh" }
    });
    (0, import_obsidian7.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.addEventListener("click", () => {
      void this.loadIssues().then(() => {
        if (this.viewMode === "kanban") this.loadContributors();
        this.render();
        new import_obsidian7.Notice("Paperclip: refreshed");
      });
    });
  }
  renderRelatedIssues(container) {
    var _a;
    if (this.relatedIssues.length === 0 || !this.relatedFilePath) return;
    const basename = (_a = this.relatedFilePath.split("/").pop()) != null ? _a : this.relatedFilePath;
    const name = basename.replace(/\.[^.]+$/, "");
    const section = container.createDiv({ cls: "paperclip-related" });
    const groupKey = "related:file";
    const collapsed = this.collapsedGroups.has(groupKey);
    const header = section.createDiv({
      cls: `paperclip-related-header paperclip-collapsible${collapsed ? " is-collapsed" : ""}`
    });
    const chevron = header.createSpan({ cls: "paperclip-collapse-icon" });
    (0, import_obsidian7.setIcon)(chevron, collapsed ? "chevron-right" : "chevron-down");
    const icon = header.createSpan({ cls: "paperclip-related-icon" });
    (0, import_obsidian7.setIcon)(icon, "file-text");
    header.createSpan({ text: `${name}`, cls: "paperclip-related-name" });
    header.createSpan({
      text: `${this.relatedIssues.length}`,
      cls: "paperclip-related-count"
    });
    header.addEventListener("click", () => {
      if (this.collapsedGroups.has(groupKey)) {
        this.collapsedGroups.delete(groupKey);
      } else {
        this.collapsedGroups.add(groupKey);
      }
      this.render();
    });
    if (!collapsed) {
      const list = section.createDiv({ cls: "paperclip-issue-list" });
      for (const issue of this.relatedIssues) {
        this.renderIssueRow(list, issue);
      }
    }
  }
  renderListBody(container) {
    var _a, _b, _c;
    const list = container.createDiv({ cls: "paperclip-issue-list" });
    if (this.issues.length === 0) {
      list.createDiv({
        cls: "paperclip-empty",
        text: "No issues found"
      });
      return;
    }
    const sorted = [...this.issues].sort(
      (a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
    );
    if (this.groupBy === "status") {
      const statusOrder = KANBAN_STATUSES;
      const groups = /* @__PURE__ */ new Map();
      for (const issue of sorted) {
        if (!groups.has(issue.status)) groups.set(issue.status, []);
        groups.get(issue.status).push(issue);
      }
      for (const status of statusOrder) {
        const groupIssues = groups.get(status);
        if (!groupIssues || groupIssues.length === 0) continue;
        this.renderCollapsibleGroup(
          list,
          `status:${status}`,
          `${status.replace("_", " ")} (${groupIssues.length})`,
          groupIssues
        );
      }
    } else if (this.groupBy === "assignee") {
      const groups = /* @__PURE__ */ new Map();
      for (const issue of sorted) {
        const key = (_a = issue.assigneeAgentId) != null ? _a : "__unassigned__";
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key).push(issue);
      }
      for (const [agentId, groupIssues] of groups) {
        const name = agentId === "__unassigned__" ? "Unassigned" : this.agentName(agentId);
        this.renderCollapsibleGroup(
          list,
          `agent:${agentId}`,
          `${name} (${groupIssues.length})`,
          groupIssues
        );
      }
    } else if (this.groupBy === "project" && !this.selectedProjectId && this.projects.length > 0) {
      const groups = /* @__PURE__ */ new Map();
      for (const issue of sorted) {
        const key = (_b = issue.projectId) != null ? _b : "__none__";
        if (!groups.has(key)) groups.set(key, []);
        groups.get(key).push(issue);
      }
      for (const [projectId, groupIssues] of groups) {
        const name = projectId === "__none__" ? "No project" : (_c = this.projectName(projectId)) != null ? _c : "Unknown project";
        this.renderCollapsibleGroup(
          list,
          `proj:${projectId}`,
          name,
          groupIssues
        );
      }
    } else {
      for (const issue of sorted) {
        this.renderIssueRow(list, issue);
      }
    }
  }
  renderCollapsibleGroup(container, groupKey, label, issues) {
    const collapsed = this.collapsedGroups.has(groupKey);
    const header = container.createDiv({
      cls: `paperclip-project-header paperclip-collapsible${collapsed ? " is-collapsed" : ""}`
    });
    const chevron = header.createSpan({ cls: "paperclip-collapse-icon" });
    (0, import_obsidian7.setIcon)(chevron, collapsed ? "chevron-right" : "chevron-down");
    header.createSpan({ text: label });
    header.addEventListener("click", () => {
      if (this.collapsedGroups.has(groupKey)) {
        this.collapsedGroups.delete(groupKey);
      } else {
        this.collapsedGroups.add(groupKey);
      }
      this.render();
    });
    if (!collapsed) {
      for (const issue of issues) {
        this.renderIssueRow(container, issue);
      }
    }
  }
  renderIssueRow(container, issue) {
    var _a, _b;
    const isRunning = issue.activeRun !== null && ((_a = issue.activeRun) == null ? void 0 : _a.status) === "running";
    const rowCls = `paperclip-issue-row${isRunning ? " is-running" : ""}`;
    const row = container.createDiv({ cls: rowCls });
    row.addEventListener("click", () => {
      this.selectedIssue = issue;
      void this.loadComments(issue.id).then(() => this.render());
    });
    const left = row.createDiv({ cls: "paperclip-issue-left" });
    if (isRunning) {
      left.createSpan({ cls: "paperclip-running-dot" });
    }
    left.createSpan({
      cls: "paperclip-issue-id",
      text: issue.identifier
    });
    left.createSpan({
      cls: "paperclip-issue-title",
      text: issue.title
    });
    const right = row.createDiv({ cls: "paperclip-issue-right" });
    if (isRunning) {
      right.createSpan({
        cls: "paperclip-running-label",
        text: this.agentName(issue.activeRun.agentId) + " working\u2026"
      });
    }
    right.createSpan({
      cls: `paperclip-status paperclip-status-${issue.status}`,
      text: issue.status.replace("_", " ")
    });
    if (issue.priority) {
      const priIcon = right.createSpan({
        cls: `paperclip-priority paperclip-priority-${issue.priority}`,
        attr: { "aria-label": issue.priority }
      });
      const iconMap = {
        critical: "chevrons-up",
        high: "chevron-up",
        medium: "minus",
        low: "chevron-down"
      };
      (0, import_obsidian7.setIcon)(priIcon, (_b = iconMap[issue.priority]) != null ? _b : "minus");
    }
    right.createSpan({
      cls: "paperclip-assignee",
      text: this.agentName(issue.assigneeAgentId)
    });
  }
  // ── Kanban ─────────────────────────────────────────────────────
  renderKanban(container) {
    const board = container.createDiv({ cls: "kb-board" });
    for (const status of KANBAN_STATUSES) {
      const colIssues = this.issues.filter((i) => i.status === status).sort(
        (a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
      );
      const col = board.createDiv({ cls: "kb-col" });
      col.dataset.status = status;
      const colHeader = col.createDiv({ cls: "kb-col-header" });
      colHeader.createSpan({
        cls: `kb-col-title`,
        text: status.replace("_", " ")
      });
      colHeader.createSpan({
        cls: "kb-col-count",
        text: String(colIssues.length)
      });
      const colBody = col.createDiv({ cls: "kb-col-body" });
      colBody.addEventListener("dragover", (e) => {
        e.preventDefault();
        colBody.addClass("kb-drag-over");
      });
      colBody.addEventListener("dragleave", () => {
        colBody.removeClass("kb-drag-over");
      });
      colBody.addEventListener("drop", (e) => {
        var _a;
        e.preventDefault();
        colBody.removeClass("kb-drag-over");
        const issueId = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
        if (!issueId) return;
        const issue = this.issues.find((i) => i.id === issueId);
        if (!issue || issue.status === status) return;
        void this.plugin.api.updateIssue(issueId, { status }).then(() => {
          issue.status = status;
          new import_obsidian7.Notice(`${issue.identifier} \u2192 ${status.replace("_", " ")}`);
          this.render();
        }).catch((err) => {
          new import_obsidian7.Notice(`Failed: ${err}`);
        });
      });
      for (const issue of colIssues) {
        this.renderKanbanCard(colBody, issue);
      }
    }
  }
  renderKanbanCard(container, issue) {
    var _a, _b, _c;
    const isRunning = issue.activeRun !== null && ((_a = issue.activeRun) == null ? void 0 : _a.status) === "running";
    const card = container.createDiv({
      cls: `kb-card${isRunning ? " is-running" : ""}`
    });
    card.draggable = true;
    card.dataset.issueId = issue.id;
    card.addEventListener("dragstart", (e) => {
      var _a2;
      (_a2 = e.dataTransfer) == null ? void 0 : _a2.setData("text/plain", issue.id);
      card.addClass("kb-dragging");
    });
    card.addEventListener("dragend", () => {
      card.removeClass("kb-dragging");
    });
    card.addEventListener("click", () => {
      this.selectedIssue = issue;
      void this.loadComments(issue.id).then(() => this.render());
    });
    const topRow = card.createDiv({ cls: "kb-card-top" });
    if (isRunning) {
      topRow.createSpan({ cls: "paperclip-running-dot" });
    }
    topRow.createSpan({ cls: "kb-card-id", text: issue.identifier });
    if (issue.priority) {
      const priIcon = topRow.createSpan({
        cls: `paperclip-priority paperclip-priority-${issue.priority}`
      });
      const iconMap = {
        critical: "chevrons-up",
        high: "chevron-up",
        medium: "minus",
        low: "chevron-down"
      };
      (0, import_obsidian7.setIcon)(priIcon, (_b = iconMap[issue.priority]) != null ? _b : "minus");
    }
    card.createDiv({ cls: "kb-card-title", text: issue.title });
    const proj = this.projectName(issue.projectId);
    if (proj) {
      card.createDiv({ cls: "kb-card-project", text: proj });
    }
    const bottomRow = card.createDiv({ cls: "kb-card-bottom" });
    const contribs = (_c = this.contributors.get(issue.id)) != null ? _c : [];
    if (contribs.length > 0) {
      const avatars = bottomRow.createDiv({ cls: "kb-avatars" });
      for (const agentId of contribs.slice(0, 5)) {
        const av = avatars.createSpan({
          cls: "kb-avatar",
          text: this.agentInitials(agentId)
        });
        av.title = this.agentName(agentId);
      }
      if (contribs.length > 5) {
        avatars.createSpan({
          cls: "kb-avatar kb-avatar-more",
          text: `+${contribs.length - 5}`
        });
      }
    } else if (issue.assigneeAgentId) {
      const avatars = bottomRow.createDiv({ cls: "kb-avatars" });
      const av = avatars.createSpan({
        cls: "kb-avatar",
        text: this.agentInitials(issue.assigneeAgentId)
      });
      av.title = this.agentName(issue.assigneeAgentId);
    }
    if (isRunning) {
      bottomRow.createSpan({
        cls: "paperclip-running-label",
        text: "working\u2026"
      });
    }
  }
  renderDetail(container) {
    var _a, _b, _c;
    const issue = this.selectedIssue;
    const nav = container.createDiv({ cls: "paperclip-detail-nav" });
    const backBtn = nav.createEl("button", {
      text: "\u2190 Back",
      cls: "paperclip-back"
    });
    backBtn.addEventListener("click", () => {
      this.selectedIssue = null;
      this.render();
    });
    const isRunning = issue.activeRun !== null && ((_a = issue.activeRun) == null ? void 0 : _a.status) === "running";
    if (isRunning) {
      const banner = container.createDiv({ cls: "paperclip-run-banner" });
      banner.createSpan({ cls: "paperclip-running-dot" });
      const bannerText = banner.createSpan({ cls: "paperclip-run-banner-text" });
      bannerText.setText(
        `${this.agentName(issue.activeRun.agentId)} is working on this \u2014 started ${this.relativeTime(issue.activeRun.startedAt)}`
      );
    }
    const hdr = container.createDiv({ cls: "paperclip-detail-header" });
    const titleEl = hdr.createEl("h3", {
      cls: "paperclip-detail-title"
    });
    titleEl.createSpan({ cls: "paperclip-issue-id", text: issue.identifier + "  " });
    const titleText = titleEl.createSpan({ text: issue.title, cls: "paperclip-title-editable" });
    titleText.title = "Click to rename";
    titleText.addEventListener("click", () => {
      this.startTitleEdit(issue, titleEl);
    });
    const props = container.createDiv({ cls: "paperclip-detail-props" });
    const statusRow = props.createDiv({ cls: "paperclip-prop-row" });
    statusRow.createSpan({ cls: "paperclip-prop-label", text: "Status" });
    const statusChip = statusRow.createSpan({
      cls: `paperclip-status paperclip-status-${issue.status} paperclip-status-clickable`,
      text: issue.status.replace("_", " ")
    });
    statusChip.title = "Click to change status";
    statusChip.addEventListener("click", () => {
      this.openStatusMenu(issue, statusChip);
    });
    const priRow = props.createDiv({ cls: "paperclip-prop-row" });
    priRow.createSpan({ cls: "paperclip-prop-label", text: "Priority" });
    const priChip = priRow.createSpan({
      cls: "paperclip-assignee-chip",
      text: (_b = issue.priority) != null ? _b : "none"
    });
    priChip.title = "Click to change priority";
    priChip.addEventListener("click", () => {
      this.openPriorityMenu(issue, priChip);
    });
    const assignRow = props.createDiv({ cls: "paperclip-prop-row" });
    assignRow.createSpan({ cls: "paperclip-prop-label", text: "Assignee" });
    const isAssignedToMe = issue.assigneeAgentId === null && issue.assigneeUserId === "local-board";
    const assigneeChip = assignRow.createSpan({
      cls: "paperclip-assignee-chip",
      text: isAssignedToMe ? "You" : this.agentName(issue.assigneeAgentId)
    });
    assigneeChip.addEventListener("click", () => {
      this.openAssignModal(issue);
    });
    assigneeChip.title = "Click to reassign";
    const projRow = props.createDiv({ cls: "paperclip-prop-row" });
    projRow.createSpan({ cls: "paperclip-prop-label", text: "Project" });
    const projChip = projRow.createSpan({
      cls: "paperclip-assignee-chip",
      text: (_c = this.projectName(issue.projectId)) != null ? _c : "None"
    });
    projChip.addEventListener("click", () => {
      this.openProjectModal(issue);
    });
    projChip.title = "Click to change project";
    if (issue.description) {
      const descEl = container.createDiv({
        cls: "paperclip-description"
      });
      import_obsidian7.MarkdownRenderer.render(
        this.app,
        issue.description,
        descEl,
        "",
        this
      );
      this.linkifyVaultPaths(descEl);
    }
    const actions = container.createDiv({ cls: "paperclip-actions" });
    const commentBtn = actions.createEl("button", {
      text: "Add comment",
      cls: "mod-cta"
    });
    commentBtn.addEventListener("click", () => {
      this.openCommentModal(issue);
    });
    const thread = container.createDiv({ cls: "paperclip-comments" });
    thread.createEl("h4", { text: `Activity (${this.comments.length})` });
    if (this.comments.length === 0) {
      thread.createDiv({
        cls: "paperclip-empty",
        text: "No activity yet"
      });
    } else {
      for (const c of this.comments) {
        const isAgent = !!c.authorAgentId;
        const author = isAgent ? this.agentName(c.authorAgentId) : c.authorUserId === "local-board" ? "You" : c.authorUserId || "Board";
        const initials = author.split(/\s+/).map((w) => w[0]).join("").toUpperCase().slice(0, 2);
        const card = thread.createDiv({
          cls: `paperclip-comment ${isAgent ? "is-agent" : "is-user"}`
        });
        const cHeader = card.createDiv({ cls: "paperclip-comment-header" });
        const avatar = cHeader.createSpan({
          cls: `paperclip-comment-avatar ${isAgent ? "is-agent" : "is-user"}`,
          text: initials
        });
        avatar.title = author;
        const headerText = cHeader.createDiv({ cls: "paperclip-comment-meta" });
        headerText.createSpan({
          cls: "paperclip-comment-author",
          text: author
        });
        const dateSpan = headerText.createSpan({
          cls: "paperclip-comment-date",
          text: this.relativeTime(c.createdAt)
        });
        dateSpan.title = new Date(c.createdAt).toLocaleString();
        const cBody = card.createDiv({ cls: "paperclip-comment-body" });
        import_obsidian7.MarkdownRenderer.render(
          this.app,
          c.body,
          cBody,
          "",
          this
        );
        this.linkifyVaultPaths(cBody);
      }
    }
  }
  /** Convert file paths in rendered markdown <code> elements into clickable vault links */
  linkifyVaultPaths(el) {
    var _a;
    const codeEls = el.querySelectorAll("code");
    for (const code of Array.from(codeEls)) {
      const text = (_a = code.textContent) != null ? _a : "";
      if (!text.includes("/") && !/\.(md|txt|pdf|png|jpg|csv|json|yaml|yml)$/i.test(text)) continue;
      const file = this.app.vault.getAbstractFileByPath(text);
      if (!file) continue;
      code.addClass("paperclip-vault-link");
      code.title = `Open ${text}`;
      code.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.app.workspace.openLinkText(text, "");
      });
    }
  }
  startTitleEdit(issue, container) {
    container.empty();
    container.createSpan({ cls: "paperclip-issue-id", text: issue.identifier + "  " });
    const input = container.createEl("input", {
      cls: "paperclip-title-input",
      type: "text",
      value: issue.title
    });
    input.focus();
    input.select();
    const save = async () => {
      const newTitle = input.value.trim();
      if (!newTitle || newTitle === issue.title) {
        this.render();
        return;
      }
      try {
        await this.plugin.api.updateIssue(issue.id, { title: newTitle });
        issue.title = newTitle;
        const idx = this.issues.findIndex((i) => i.id === issue.id);
        if (idx >= 0) this.issues[idx] = { ...this.issues[idx], title: newTitle };
        new import_obsidian7.Notice("Title updated");
      } catch (e) {
        new import_obsidian7.Notice(`Failed: ${e}`);
      }
      this.render();
    };
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void save();
      } else if (e.key === "Escape") {
        this.render();
      }
    });
    input.addEventListener("blur", () => {
      void save();
    });
  }
  // ── Modal helpers ──────────────────────────────────────────────────
  openCommentModal(issue) {
    new CommentModal(this.app, issue, this.agents, (result) => {
      const action = result.assignAgentId ? this.plugin.api.updateIssue(issue.id, {
        assigneeAgentId: result.assignAgentId,
        assigneeUserId: null,
        comment: result.body
      }).then(() => {
        var _a, _b;
        issue.assigneeAgentId = (_a = result.assignAgentId) != null ? _a : null;
        const agentName = this.agentName((_b = result.assignAgentId) != null ? _b : null);
        new import_obsidian7.Notice(`Comment posted & assigned to ${agentName}`);
      }) : this.plugin.api.addComment(issue.id, result.body).then(() => {
        new import_obsidian7.Notice("Comment posted");
      });
      void action.then(() => this.loadComments(issue.id)).then(() => this.render()).catch((e) => {
        new import_obsidian7.Notice(`Failed: ${e}`);
      });
    }).open();
  }
  openCreateIssueModal() {
    const activeFile = this.app.workspace.getActiveFile();
    const filePath = activeFile ? activeFile.path : null;
    new CreateIssueModal(
      this.app,
      this.agents,
      this.projects,
      filePath,
      this.selectedProjectId,
      async (result) => {
        try {
          const data = {
            title: result.title,
            description: result.description,
            priority: result.priority,
            status: "todo"
          };
          if (result.assignToMe) {
          } else if (result.assigneeAgentId) {
            data.assigneeAgentId = result.assigneeAgentId;
          }
          if (result.projectId) {
            data.projectId = result.projectId;
          }
          const created = await this.plugin.api.createIssue(
            this.selectedCompanyId,
            data
          );
          if (result.assignToMe) {
            await this.plugin.api.updateIssue(created.id, {
              assigneeUserId: "local-board"
            });
          }
          new import_obsidian7.Notice("Issue created");
          await this.loadIssues();
          this.render();
        } catch (e) {
          new import_obsidian7.Notice(`Failed to create issue: ${e}`);
        }
      }
    ).open();
  }
  openPriorityMenu(issue, anchor) {
    const menu = new import_obsidian7.Menu();
    const priorities = ["critical", "high", "medium", "low"];
    const labels = { critical: "Critical", high: "High", medium: "Medium", low: "Low" };
    for (const p of priorities) {
      menu.addItem((item) => {
        item.setTitle(labels[p]).setChecked(issue.priority === p).onClick(() => {
          if (issue.priority === p) return;
          void this.plugin.api.updateIssue(issue.id, {
            priority: p
          }).then(() => {
            issue.priority = p;
            new import_obsidian7.Notice(`Priority \u2192 ${labels[p]}`);
            this.render();
          }).catch((e) => {
            new import_obsidian7.Notice(`Failed: ${e}`);
          });
        });
      });
    }
    const rect = anchor.getBoundingClientRect();
    menu.showAtPosition({ x: rect.left, y: rect.bottom });
  }
  openStatusMenu(issue, anchor) {
    const menu = new import_obsidian7.Menu();
    const statuses = [
      "backlog",
      "todo",
      "in_progress",
      "in_review",
      "blocked",
      "done",
      "cancelled"
    ];
    const statusLabel = (s) => {
      const words = s.split("_");
      return words[0].charAt(0).toUpperCase() + words[0].slice(1) + (words.length > 1 ? " " + words.slice(1).join(" ") : "");
    };
    for (const s of statuses) {
      menu.addItem((item) => {
        item.setTitle(statusLabel(s)).setChecked(issue.status === s).onClick(() => {
          if (issue.status === s) return;
          void this.plugin.api.updateIssue(issue.id, {
            status: s
          }).then(() => {
            issue.status = s;
            new import_obsidian7.Notice(`Status \u2192 ${statusLabel(s)}`);
            this.render();
          }).catch((e) => {
            new import_obsidian7.Notice(`Failed: ${e}`);
          });
        });
      });
    }
    const rect = anchor.getBoundingClientRect();
    menu.showAtPosition({ x: rect.left, y: rect.bottom });
  }
  openProjectModal(issue) {
    new ProjectModal(
      this.app,
      this.projects,
      (project) => {
        var _a;
        void this.plugin.api.updateIssue(issue.id, {
          projectId: (_a = project == null ? void 0 : project.id) != null ? _a : null,
          projectWorkspaceId: null
        }).then(() => {
          var _a2;
          issue.projectId = (_a2 = project == null ? void 0 : project.id) != null ? _a2 : null;
          new import_obsidian7.Notice(
            project ? `Project: ${project.name}` : "Project removed"
          );
          this.render();
        }).catch((e) => {
          new import_obsidian7.Notice(`Failed to set project: ${e}`);
        });
      },
      async (name) => {
        const p = await this.plugin.api.createProject(
          this.selectedCompanyId,
          name
        );
        this.projects.push(p);
        return p;
      }
    ).open();
  }
  openAssignModal(issue) {
    new AssignModal(this.app, this.agents, (agent, special) => {
      var _a;
      const doAssign = special === ASSIGN_TO_ME ? this.plugin.api.updateIssue(issue.id, {
        assigneeAgentId: null,
        assigneeUserId: "local-board"
      }).then(() => {
        issue.assigneeAgentId = null;
        issue.assigneeUserId = "local-board";
        new import_obsidian7.Notice("Assigned to you");
      }) : this.plugin.api.updateIssue(issue.id, {
        assigneeAgentId: (_a = agent == null ? void 0 : agent.id) != null ? _a : null,
        assigneeUserId: null
      }).then(() => {
        var _a2;
        issue.assigneeAgentId = (_a2 = agent == null ? void 0 : agent.id) != null ? _a2 : null;
        issue.assigneeUserId = null;
        new import_obsidian7.Notice(
          agent ? `Assigned to ${agent.name}` : "Unassigned"
        );
      });
      void doAssign.then(() => {
        var _a2;
        const idx = this.issues.findIndex((i) => i.id === issue.id);
        if (idx >= 0) this.issues[idx] = { ...issue };
        if (((_a2 = this.selectedIssue) == null ? void 0 : _a2.id) === issue.id) {
          this.selectedIssue = { ...issue };
        }
        this.render();
      }).catch((e) => {
        new import_obsidian7.Notice(`Failed to assign: ${e}`);
      });
    }).open();
  }
};

// src/main.ts
var PaperclipPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.api = new PaperclipApi(DEFAULT_SETTINGS.apiBaseUrl);
  }
  async onload() {
    await this.loadSettings();
    this.api = new PaperclipApi(
      this.settings.apiBaseUrl,
      this.settings.apiKey || void 0
    );
    this.registerView(VIEW_TYPE, (leaf) => new PaperclipView(leaf, this));
    this.addRibbonIcon("paperclip", "Open Paperclip", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-issue-browser",
      name: "Open issue browser",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "create-issue",
      name: "Create issue",
      callback: () => {
        void this.openCreateIssue();
      }
    });
    this.addCommand({
      id: "work-on-document",
      name: "Work on this document (AI)",
      checkCallback: (checking) => {
        if (!this.app.workspace.getActiveFile()) return false;
        if (!checking) void this.createIssueWithAI("", "work");
        return true;
      }
    });
    this.addCommand({
      id: "review-document",
      name: "Review this document (AI)",
      checkCallback: (checking) => {
        if (!this.app.workspace.getActiveFile()) return false;
        if (!checking) void this.createIssueWithAI("", "review");
        return true;
      }
    });
    this.addCommand({
      id: "smart-action",
      name: "Smart action (AI)",
      editorCallback: (editor) => {
        var _a;
        const sel = ((_a = editor.getSelection()) == null ? void 0 : _a.trim()) || "";
        void this.createIssueWithAI(sel, "auto");
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        var _a;
        const sel = ((_a = editor.getSelection()) == null ? void 0 : _a.trim()) || "";
        const file = this.app.workspace.getActiveFile();
        if (!file) return;
        if (sel) {
          menu.addItem((item) => {
            item.setTitle("\u{1F4CE} Create issue from selection").setIcon("paperclip").onClick(() => {
              void this.createIssueWithAI(sel, "work");
            });
          });
        } else {
          menu.addItem((item) => {
            item.setTitle("\u{1F4CE} Work on this document").setIcon("paperclip").onClick(() => {
              void this.createIssueWithAI("", "work");
            });
          });
          menu.addItem((item) => {
            item.setTitle("\u{1F4CE} Review this document").setIcon("eye").onClick(() => {
              void this.createIssueWithAI("", "review");
            });
          });
        }
      })
    );
    this.addSettingTab(new PaperclipSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.api.updateConfig(
      this.settings.apiBaseUrl,
      this.settings.apiKey || void 0
    );
  }
  async openCreateIssue() {
    var _a, _b;
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (leaves.length > 0) {
      const view = leaves[0].view;
      view.openCreateIssueModal();
      return;
    }
    try {
      const companies = await this.api.listCompanies();
      const companyId = this.settings.defaultCompanyId || ((_a = companies[0]) == null ? void 0 : _a.id);
      if (!companyId) {
        new import_obsidian8.Notice("Paperclip: no companies found");
        return;
      }
      const agents = await this.api.listAgents(companyId);
      const projects = await this.api.listProjects(companyId);
      const activeFile = this.app.workspace.getActiveFile();
      new CreateIssueModal(
        this.app,
        agents,
        projects,
        (_b = activeFile == null ? void 0 : activeFile.path) != null ? _b : null,
        "",
        async (result) => {
          try {
            const created = await this.api.createIssue(companyId, {
              title: result.title,
              description: result.description,
              priority: result.priority,
              status: "todo",
              assigneeAgentId: result.assignToMe ? void 0 : result.assigneeAgentId,
              projectId: result.projectId
            });
            if (result.assignToMe) {
              await this.api.updateIssue(created.id, { assigneeUserId: "local-board" });
            }
            new import_obsidian8.Notice("Issue created");
          } catch (e) {
            new import_obsidian8.Notice(`Failed to create issue: ${e}`);
          }
        }
      ).open();
    } catch (e) {
      new import_obsidian8.Notice(`Paperclip: ${e}`);
    }
  }
  async createIssueWithAI(selection, intent = "auto") {
    var _a, _b, _c, _d, _e, _f, _g, _h;
    const openaiKey = this.settings.openaiApiKey;
    if (!openaiKey) {
      new import_obsidian8.Notice("Paperclip: set your OpenAI API key in settings first");
      return;
    }
    try {
      let agents = [];
      let projects = [];
      let companyId = "";
      const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
      if (leaves.length > 0) {
        const view = leaves[0].view;
        agents = view.getAgents();
        projects = view.getProjects();
        companyId = view.getSelectedCompanyId();
      }
      if (!companyId) {
        const companies = await this.api.listCompanies();
        companyId = this.settings.defaultCompanyId || ((_a = companies[0]) == null ? void 0 : _a.id);
      }
      if (!companyId) {
        new import_obsidian8.Notice("Paperclip: no companies found");
        return;
      }
      if (agents.length === 0) agents = await this.api.listAgents(companyId);
      if (projects.length === 0) projects = await this.api.listProjects(companyId);
      const activeFile = this.app.workspace.getActiveFile();
      const filePath = (_b = activeFile == null ? void 0 : activeFile.path) != null ? _b : "unknown";
      let fileContent = "";
      if (activeFile) {
        try {
          fileContent = await this.app.vault.read(activeFile);
        } catch (e) {
        }
      }
      const agentList = agents.map((a) => `- ${a.name} (${a.role}): ${a.capabilities || "general"}`).join("\n");
      const projectList = projects.filter((p) => !p.archivedAt).map((p) => `- ${p.name}`).join("\n");
      const hasSelection = !!selection;
      const dotIdx = filePath.lastIndexOf(".");
      const reviewPath = dotIdx > 0 ? `${filePath.slice(0, dotIdx)} - Review${filePath.slice(dotIdx)}` : `${filePath} - Review`;
      const noticeMsg = {
        work: hasSelection ? "Creating issue from selection\u2026" : "Creating issue from document\u2026",
        review: "Preparing review request\u2026",
        auto: "Analyzing document\u2026"
      };
      new import_obsidian8.Notice(noticeMsg[intent]);
      const userContent = hasSelection ? `## Selected text
${selection}

## Full file (${filePath})
${fileContent.slice(0, 12e3)}` : `## Full document (${filePath})
${fileContent.slice(0, 12e3)}`;
      const intentPrompts = {
        work: hasSelection ? `You create actionable Paperclip issues from highlighted text. Focus on the selection but use the full file for context. The issue should describe concrete work to be done.` : `You create actionable Paperclip issues from documents. Analyze the document and create an issue for the most important work that needs to be done based on its content (implementation, follow-up, next steps, etc).`,
        review: `You create Paperclip review issues. The user wants a thorough review of this document. The review should be written into a new file at \`${reviewPath}\`. Include in the description: what to review, what to look for, and where to write the output.`,
        auto: `You analyze documents and create the most appropriate Paperclip issue. Determine whether the document needs: follow-up work, a review, implementation, or something else. Then create the best-fit issue. If it looks like meeting notes or a report, create follow-up actions. If it looks like a spec or plan, create implementation tasks. If it looks like a draft, suggest a review.`
      };
      const resp = await (0, import_obsidian8.requestUrl)({
        url: "https://api.openai.com/v1/chat/completions",
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${openaiKey}`
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          temperature: 0.3,
          response_format: { type: "json_object" },
          messages: [
            {
              role: "system",
              content: `${intentPrompts[intent]}

Return JSON with:
- "title": concise issue title (max 80 chars)
- "description": markdown description with clear acceptance criteria. Reference the source file.
- "priority": one of "critical", "high", "medium", "low"
- "assignee": the exact name of the best-fit agent from the list below, or null
- "project": the exact name of the best-fit project from the list below, or null

Available agents:
${agentList}

Available projects:
${projectList}

File: ${filePath}`
            },
            {
              role: "user",
              content: userContent
            }
          ]
        })
      });
      const parsed = JSON.parse(
        resp.json.choices[0].message.content
      );
      const matchedAgent = parsed.assignee ? agents.find(
        (a) => a.name.toLowerCase() === parsed.assignee.toLowerCase()
      ) : null;
      const matchedProject = parsed.project ? projects.find(
        (p) => p.name.toLowerCase() === parsed.project.toLowerCase()
      ) : null;
      new CreateIssueModal(
        this.app,
        agents,
        projects,
        (_c = activeFile == null ? void 0 : activeFile.path) != null ? _c : null,
        "",
        async (result) => {
          try {
            const created = await this.api.createIssue(companyId, {
              title: result.title,
              description: result.description,
              priority: result.priority,
              status: "todo",
              assigneeAgentId: result.assignToMe ? void 0 : result.assigneeAgentId,
              projectId: result.projectId
            });
            if (result.assignToMe) {
              await this.api.updateIssue(created.id, { assigneeUserId: "local-board" });
            }
            new import_obsidian8.Notice("Issue created");
          } catch (e) {
            new import_obsidian8.Notice(`Failed to create issue: ${e}`);
          }
        },
        {
          title: (_d = parsed.title) != null ? _d : "",
          description: (_e = parsed.description) != null ? _e : "",
          priority: (_f = parsed.priority) != null ? _f : "medium",
          assigneeAgentId: (_g = matchedAgent == null ? void 0 : matchedAgent.id) != null ? _g : "",
          projectId: (_h = matchedProject == null ? void 0 : matchedProject.id) != null ? _h : ""
        }
      ).open();
    } catch (e) {
      new import_obsidian8.Notice(`AI issue creation failed: ${e}`);
    }
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
  }
};
